// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xlsakesvpxelktbyawul.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inhsc2FrZXN2cHhlbGt0Ynlhd3VsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTcwODM5MDEsImV4cCI6MjA3MjY1OTkwMX0._7ZrrgaGbnoiu5njaij7fw9P0EBYeyEIq8S6iErmLjE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});